version: '3'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:5123:5123"
    network_mode: host
    restart: unless-stopped

  fetcher:
    build: .
    network_mode: host
    command: dotnet Fetcher.dll
